const brainrotTerms = [
  {
    title: "Skibidi Toilet War",
    creationYear: 2023,
    platform: "TikTok, YouTube",
    imageUrl: "",
    altText: "",
  },
  {
    title: "Only in Ohio",
    creationYear: 2023,
    platform: "TikTok, Twitter",
    imageUrl: "",
    altText: "",
  },
  {
    title: "Fanum Tax",
    creationYear: 2023,
    platform: "TikTok, Twitch",
    imageUrl: "",
    altText: "",
  },
  {
    title: "Grimace Birthday Shake",
    creationYear: 2023,
    platform: "TikTok, Twitter",
    imageUrl: "",
    altText: "",
  },
  {
    title: "Rizz God",
    creationYear: 2022,
    platform: "TikTok",
    imageUrl: "",
    altText: "",
  },
  {
    title: "Goofy Ahh Universe",
    creationYear: 2023,
    platform: "TikTok, YouTube",
    imageUrl: "",
    altText: "",
  },
  {
    title: "Sigma Male Grindset",
    creationYear: 2021,
    platform: "TikTok, YouTube",
    imageUrl: "",
    altText: "",
  },
  {
    title: "NPC TikTok Lives",
    creationYear: 2023,
    platform: "TikTok",
    imageUrl: "",
    altText: "",
  },
  {
    title: "Bussin' Respectfully",
    creationYear: 2022,
    platform: "TikTok",
    imageUrl: "",
    altText: "",
  },
  {
    title: "Goblin Mode Unlocked",
    creationYear: 2022,
    platform: "Twitter, Instagram",
    imageUrl: "",
    altText: "",
  },
  {
    title: "CEO of...",
    creationYear: 2020,
    platform: "TikTok",
    imageUrl: "",
    altText: "",
  },
  {
    title: "Shiver Me Timbers",
    creationYear: 2023,
    platform: "TikTok, YouTube",
    imageUrl: "",
    altText: "",
  },
  {
    title: "Ratio + Touch Grass",
    creationYear: 2022,
    platform: "Twitter",
    imageUrl: "",
    altText: "",
  },
  {
    title: "Ohio Final Boss",
    creationYear: 2023,
    platform: "TikTok, YouTube",
    imageUrl: "",
    altText: "",
  },
  {
    title: "Canon Event",
    creationYear: 2023,
    platform: "TikTok, Instagram",
    imageUrl: "",
    altText: "",
  },
  {
    title: "ChadGPT",
    creationYear: 2023,
    platform: "Reddit, Twitter",
    imageUrl: "",
    altText: "",
  },
  {
    title: "NPC Energy",
    creationYear: 2023,
    platform: "TikTok, YouTube",
    imageUrl: "",
    altText: "",
  },
  {
    title: "Silent Rizz",
    creationYear: 2023,
    platform: "TikTok",
    imageUrl: "",
    altText: "",
  },
  {
    title: "Dabloons Economy",
    creationYear: 2022,
    platform: "TikTok",
    imageUrl: "",
    altText: "",
  },
  {
    title: "Sussy Baka",
    creationYear: 2021,
    platform: "Among Us, TikTok",
    imageUrl: "",
    altText: "",
  },
];
